version: '2'
services:
  web:
    build: .
    command: npm start -- --hostname 0.0.0.0 --port 4444
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8081:4444"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://todoapp@postgres/todos
  # postgres:
  #   image: postgres:9.6.2-alpine
  #   environment:
  #     POSTGRES_USER: todoapp
  #     POSTGRES_DB: todos